//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurrance_Application_Proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearInsurrance
    {
        public int Id { get; set; }
        public string Customer { get; set; }
        public Nullable<int> Insurrance { get; set; }
        public Nullable<int> Day { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Funder { get; set; }
    
        public virtual RegCustomer RegCustomer { get; set; }
        public virtual Insurrance Insurrance1 { get; set; }
        public virtual Funder Funder1 { get; set; }
    }
}
