//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurrance_Application_Proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegHospital
    {
        public RegHospital()
        {
            this.PayHospitals = new HashSet<PayHospital>();
            this.TreatCustomers = new HashSet<TreatCustomer>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RegDay { get; set; }
        public string RegMonth { get; set; }
        public Nullable<int> RegYear { get; set; }
        public string District { get; set; }
        public string Account { get; set; }
        public string Bank { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
    
        public virtual ICollection<PayHospital> PayHospitals { get; set; }
        public virtual ICollection<TreatCustomer> TreatCustomers { get; set; }
    }
}
